services:
  jenkins:
    container_name: jenkins
    build:
      context: ./jenkins
    ports:
      - "8080:8080"
    volumes:
      - ./jenkins/home:/var/jenkins_home
      - D:/Projects/PHP:/projects/php
      - D:/Projects/Go:/projects/go
    environment:
      - JENKINS_OPTS=--httpPort=8080
    networks:
      - jenkins_network
    depends_on:
      - sonarqube
      - db
    # restart: always

  sonarqube:
    container_name: sonarqube
    image: sonarqube:community
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    volumes:
      - ./sonarqube/data:/opt/sonarqube/data
      - ./sonarqube/extensions:/opt/sonarqube/extensions
      - ./sonarqube/logs:/opt/sonarqube/logs

  db:
    container_name: sonarqube_db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
networks:
  jenkins_network:
    driver: bridge